name: Cloud PC AnyViewer (Gotowy)
on: workflow_dispatch

jobs:
  run-pc:
    runs-on: windows-latest
    steps:
      - name: 1. Instalacja Wirtualnej Grafiki i Kontrolera
        shell: powershell
        run: |
          winget install "IddSampleDriver" --accept-source-agreements --accept-package-agreements
          winget install "ViGEmBus" --accept-source-agreements --accept-package-agreements

      - name: 2. Pobieranie i instalacja AnyViewer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://dl.anyviewer.com/AnyViewerSetup.exe" -OutFile "anyviewer_setup.exe"
          Start-Process -FilePath ".\anyviewer_setup.exe" -ArgumentList "/S" -Wait

      - name: 3. Logowanie i uruchomienie serwera
        shell: powershell
        run: |
          cd "C:\Program Files (x86)\AnyViewer"
          
          # Automatyczne logowanie na Twoje konto
          $email = "Robloxqwru@gmail.com"
          $password = "termi4231"
          
          Start-Process -FilePath ".\AnyViewer.exe" -ArgumentList "/login", $email, $password
          Write-Host "Zalogowano pomyslnie na: $email"

      - name: 4. Podtrzymanie sesji
        shell: powershell
        run: Start-Sleep -Seconds 20000
